import { type Food, FoodType } from '@/@types/diet'

export const DIET_STORAGE_KEY = '@fitaura:diet'
export const CUSTOM_FOODS_STORAGE_KEY = '@fitaura:custom_foods'

export const DEFAULT_FOODS: Food[] = [
  {
    id: 'arroz',
    name: 'Arroz cozido',
    type: FoodType.Solid,
    caloriesPer1Unit: 1.28,
    proteinPer1Unit: 0.026,
    carbsPer1Unit: 0.28,
    fatPer1Unit: 0.001,
  },
  {
    id: 'feijao',
    name: 'Feijão cozido',
    type: FoodType.Solid,
    caloriesPer1Unit: 0.77,
    proteinPer1Unit: 0.049,
    carbsPer1Unit: 0.138,
    fatPer1Unit: 0.005,
  },
  {
    id: 'frango',
    name: 'Frango grelhado',
    type: FoodType.Solid,
    caloriesPer1Unit: 1.65,
    proteinPer1Unit: 0.31,
    carbsPer1Unit: 0.0,
    fatPer1Unit: 0.036,
  },
  {
    id: 'carne-moida',
    name: 'Carne moída',
    type: FoodType.Solid,
    caloriesPer1Unit: 2.0,
    proteinPer1Unit: 0.26,
    carbsPer1Unit: 0.0,
    fatPer1Unit: 0.11,
  },
  {
    id: 'batata-doce',
    name: 'Batata doce',
    type: FoodType.Solid,
    caloriesPer1Unit: 0.86,
    proteinPer1Unit: 0.016,
    carbsPer1Unit: 0.2,
    fatPer1Unit: 0.001,
  },
  {
    id: 'aveia',
    name: 'Aveia',
    type: FoodType.Solid,
    caloriesPer1Unit: 3.89,
    proteinPer1Unit: 0.117,
    carbsPer1Unit: 0.662,
    fatPer1Unit: 0.07,
  },
  {
    id: 'whey',
    name: 'Whey protein',
    type: FoodType.Solid,
    caloriesPer1Unit: 3.7,
    proteinPer1Unit: 0.75,
    carbsPer1Unit: 0.06,
    fatPer1Unit: 0.04,
  },
  {
    id: 'iogurte',
    name: 'Iogurte natural',
    type: FoodType.Solid,
    caloriesPer1Unit: 0.61,
    proteinPer1Unit: 0.035,
    carbsPer1Unit: 0.047,
    fatPer1Unit: 0.032,
  },
  {
    id: 'batata-frita',
    name: 'Batata frita',
    type: FoodType.Solid,
    caloriesPer1Unit: 3.12,
    proteinPer1Unit: 0.034,
    carbsPer1Unit: 0.41,
    fatPer1Unit: 0.15,
  },
  {
    id: 'queijo-mussarela',
    name: 'Queijo muçarela',
    type: FoodType.Solid,
    caloriesPer1Unit: 2.8,
    proteinPer1Unit: 0.195,
    carbsPer1Unit: 0.022,
    fatPer1Unit: 0.21,
  },
  {
    id: 'presunto',
    name: 'Presunto',
    type: FoodType.Solid,
    caloriesPer1Unit: 1.09,
    proteinPer1Unit: 0.163,
    carbsPer1Unit: 0.015,
    fatPer1Unit: 0.038,
  },
  {
    id: 'mortadela',
    name: 'Mortadela',
    type: FoodType.Solid,
    caloriesPer1Unit: 2.85,
    proteinPer1Unit: 0.125,
    carbsPer1Unit: 0.02,
    fatPer1Unit: 0.245,
  },
  {
    id: 'atum',
    name: 'Atum em lata',
    type: FoodType.Solid,
    caloriesPer1Unit: 1.28,
    proteinPer1Unit: 0.29,
    carbsPer1Unit: 0.0,
    fatPer1Unit: 0.01,
  },
  {
    id: 'salmon',
    name: 'Salmão grelhado',
    type: FoodType.Solid,
    caloriesPer1Unit: 2.08,
    proteinPer1Unit: 0.2,
    carbsPer1Unit: 0.0,
    fatPer1Unit: 0.13,
  },
  {
    id: 'macarrao',
    name: 'Macarrão cozido',
    type: FoodType.Solid,
    caloriesPer1Unit: 1.31,
    proteinPer1Unit: 0.05,
    carbsPer1Unit: 0.25,
    fatPer1Unit: 0.011,
  },
  {
    id: 'manteiga',
    name: 'Manteiga',
    type: FoodType.Solid,
    caloriesPer1Unit: 7.17,
    proteinPer1Unit: 0.009,
    carbsPer1Unit: 0.001,
    fatPer1Unit: 0.81,
  },
  {
    id: 'pao-frances',
    name: 'Pão francês',
    type: FoodType.Countable,
    caloriesPer1Unit: 150,
    proteinPer1Unit: 4.0,
    carbsPer1Unit: 29.0,
    fatPer1Unit: 1.75,
  },
  {
    id: 'hamburguer',
    name: 'Hambúrguer bovino',
    type: FoodType.Countable,
    caloriesPer1Unit: 244,
    proteinPer1Unit: 17.0,
    carbsPer1Unit: 0.0,
    fatPer1Unit: 19.0,
  },
  {
    id: 'banana',
    name: 'Banana',
    type: FoodType.Countable,
    caloriesPer1Unit: 89,
    proteinPer1Unit: 1.09,
    carbsPer1Unit: 22.8,
    fatPer1Unit: 0.33,
  },
  {
    id: 'ovo',
    name: 'Ovo',
    type: FoodType.Countable,
    caloriesPer1Unit: 70,
    proteinPer1Unit: 6.0,
    carbsPer1Unit: 0.6,
    fatPer1Unit: 4.8,
  },
  {
    id: 'maca',
    name: 'Maçã',
    type: FoodType.Countable,
    caloriesPer1Unit: 72,
    proteinPer1Unit: 0.36,
    carbsPer1Unit: 19.0,
    fatPer1Unit: 0.23,
  },
  {
    id: 'laranja',
    name: 'Laranja',
    type: FoodType.Countable,
    caloriesPer1Unit: 62,
    proteinPer1Unit: 1.2,
    carbsPer1Unit: 15.4,
    fatPer1Unit: 0.16,
  },
  {
    id: 'pera',
    name: 'Pera',
    type: FoodType.Countable,
    caloriesPer1Unit: 57,
    proteinPer1Unit: 0.36,
    carbsPer1Unit: 15.2,
    fatPer1Unit: 0.14,
  },
  {
    id: 'agua',
    name: 'Água',
    type: FoodType.Liquid,
    caloriesPer1Unit: 0,
    proteinPer1Unit: 0,
    carbsPer1Unit: 0,
    fatPer1Unit: 0,
  },
  {
    id: 'leite',
    name: 'Leite integral',
    type: FoodType.Liquid,
    caloriesPer1Unit: 0.61,
    proteinPer1Unit: 0.032,
    carbsPer1Unit: 0.047,
    fatPer1Unit: 0.033,
  },
  {
    id: 'leite-desnatado',
    name: 'Leite desnatado',
    type: FoodType.Liquid,
    caloriesPer1Unit: 0.35,
    proteinPer1Unit: 0.034,
    carbsPer1Unit: 0.05,
    fatPer1Unit: 0.001,
  },
  {
    id: 'suco-laranja',
    name: 'Suco de laranja',
    type: FoodType.Liquid,
    caloriesPer1Unit: 0.45,
    proteinPer1Unit: 0.007,
    carbsPer1Unit: 0.104,
    fatPer1Unit: 0.002,
  },
  {
    id: 'cafe',
    name: 'Café sem açúcar',
    type: FoodType.Liquid,
    caloriesPer1Unit: 0.02,
    proteinPer1Unit: 0.003,
    carbsPer1Unit: 0.0,
    fatPer1Unit: 0.0,
  },
  {
    id: 'refrigerante',
    name: 'Refrigerante cola',
    type: FoodType.Liquid,
    caloriesPer1Unit: 0.42,
    proteinPer1Unit: 0.0,
    carbsPer1Unit: 0.106,
    fatPer1Unit: 0.0,
  },
]
